### ISSUE TITLE
'NEXT' button not available at the top right hand corner at template page.

### ISSUE THREAD

**Issue by pprabakaran** [IMDA-BTG/aiverify#80]
Following ai verify quick-start-guide.pdf, I cannot find the 'NEXT' button at templates page. I have completed steps 1, 2 and I cannot complete 3 because of this bug. Kindly assist.

**Comment by kimeetok** [comment]
Hi @pprabakaran , thanks for trying out the toolkit.

Would like to better understand your issue.

Are you stuck at this screen where you have selected the Summary Report Template (box has a purple outline) but the 'Next>' button (at the top right corner) did not appear?
![image](https://github.com/IMDA-BTG/aiverify/assets/129362897/e628026c-2726-4fff-ae19-5653c334fc2d)

Also, did you build the toolkit via Dockerfile or source code?

**Comment by pprabakaran** [comment]
Hi @kimeetok , 
I am stuck at the Template edit page. I need the next button to start editing the tests parameters.

![image](https://github.com/IMDA-BTG/aiverify/assets/44604048/b7d914bf-a7d6-4544-918f-80f48f16717a)

At the top right hand corner, there should have been "NEXT" as shown in Ai Verify [documentation](https://imda-btg.github.io/aiverify/using-toolkit-step-by-step/test-ai-model-and-generate-report/3-design-the-report/)

**Comment by kimeetok** [comment]
Hi @pprabakaran 

Thanks for the screenshot. It is expected behaviour that there is no 'Next' button in the Template edit page.

The quick start guide is a tutorial for generating a report using our report template.
In this workflow, we do not edit the report template so you should not have reached the template edit page as seen in your screenshot. The correct screen would say 'Design Report' instead of 'Design Report Template'
![image](https://github.com/IMDA-BTG/aiverify/assets/129362897/b1ebe363-7d65-46ca-af7f-38d029639f75)

I believe in the template selection screen [here](https://imda-btg.github.io/aiverify/using-toolkit-step-by-step/test-ai-model-and-generate-report/2-select-template/) you might have clicked on the **edit** icon instead of **selecting the template and clicking on 'Next'**
![image](https://github.com/IMDA-BTG/aiverify/assets/129362897/4074b525-0d17-4de1-acce-d36e8d9f146e)

Please retry the workflow by creating a new project and let us know if the problem persists. A more detailed step-by-step guide can be found here [tutorial](https://imda-btg.github.io/aiverify/using-toolkit-step-by-step/test-ai-model-and-generate-report/0-intro/ ).

**Comment by imda-benedictlee** [comment]
hi @pprabakaran, may I know if the above solution by @kimeetok works for you?
